version: 2

models:
  # staging
  - name: load_ids
    description: "A list of currently loaded load ids"
    columns:
      - name: load_id
        tests:
          - unique
          - not_null
  - name: stg_event_params_original
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
  - name: stg_event_params_unpacked
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
  - name: stg_events
    columns:
      - name: event_id
        tests:
          - unique
          - not_null

