# put your secret values and credentials here. do not share this file and do not push it to github

# BigQuery source configuration

[sources.bigquery_pipeline]
location = "US"
[sources.bigquery_pipeline.credentials_info]
project_id = "please set me up!"
private_key = "please set me up!"
client_email = "please set me up!"
token_uri = "please set me up!"
dataset_name = "please set me up!"
table_name = "events"

# BigQuery destination configuration

[destination.bigquery]
location = "US"
[destination.bigquery.credentials]
project_id = "please set me up!"
private_key = "please set me up!"
client_email = "please set me up!"

# PostgreSQL configuration

[destination.postgres.credentials]
database = "please set me up!"
username = "please set me up!"
password = "please set me up!" # replace with your password
host = "please set me up!" # or the IP address location of your database
port = 0000 # set me up
connect_timeout = 15

# Redshift configuration

[destination.redshift.credentials]
database = "please set me up!"
username = "please set me up!"
password = "please set me up!" # replace with your password
host = "please set me up!" # or the IP address location of your database
port = 0000 # set me up
connect_timeout = 15

# Snowflake configuration

[destination.snowflake.credentials]
database = "please set me up!"
password = "please set me up!"
username = "please set me up!"
host = "please set me up!"

# Athena confguration

[destination.filesystem]
bucket_url ="please set me up!"

[destination.filesystem.credentials]
aws_access_key_id="please set me up!"
aws_secret_access_key="please set me up!"
region_name="please set me up!"

[destination.athena]
query_result_bucket="please set me up!"
[destination.athena.credentials]
aws_access_key_id="please set me up!"
aws_secret_access_key="please set me up!"
region_name="please set me up!"
database="please set me up!"
