version: 2

sources:
  - name: dlt_metadata
    schema: "{{ var('schema_name') }}"
    tables:
      - name: _dlt_loads
      - name: _dlt_version
        columns:
          - name: version
            tests:
              - dbt_expectations.expect_column_to_exist

  - name: ga4_select_star
    schema: "{{ var('schema_name') }}"
    tables:
      - name: events
      - name: events__event_params
        columns:
          - name: key
            quote: true
